import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { NextRequest, NextResponse } from "next/server";
import { createIranKetabPreviewPost } from "./preview-handler";
import { resetIranKetabPreviewLimiterForTests } from "./rate-limit";

const emptyData={catalogs:[],editions:[],references:[],externalLinks:[]};
const request=(url="https://www.iranketab.ir/book/1045-white-nights")=>new NextRequest("http://localhost/api/admin/books/import-links/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});
const operation=(status:"PROCESSING"|"COMPLETED"|"FAILED"="PROCESSING")=>({id:"operation-1",sourceIdentity:"iranketab:book:1045",status,leaseExpiresAt:new Date(Date.now()+60_000),expiresAt:null,result:null,errorCode:null,errorMessage:null,retryable:false,generation:1,createdAt:new Date(),updatedAt:new Date()});
const acquireOnce=()=>async()=>({kind:"ACQUIRED" as const,operation:operation()});
const noOp=async()=>undefined;

test("preview API rejects unauthenticated and regular users before fetching",async()=>{for(const [status,code] of [[401,"UNAUTHENTICATED"],[403,"FORBIDDEN"]] as const){let fetched=false;const handler=createIranKetabPreviewPost({authorize:async()=>({error:NextResponse.json({ok:false,code},{status})}) as never,secureFetch:async()=>{fetched=true;throw new Error();},acquirePreviewOperation:acquireOnce(),loadAnalysisData:async()=>emptyData});const response=await handler(request());assert.equal(response.status,status);assert.equal(fetched,false);}});
test("preview API accepts an authorized admin without persistence",async()=>{resetIranKetabPreviewLimiterForTests();const html=await readFile("packages/iranketab-extractor/fixtures/white-nights/raw-page.html","utf8");const handler=createIranKetabPreviewPost({authorize:async()=>({user:{id:"admin-1"}}) as never,secureFetch:async canonicalUrl=>({canonicalUrl,html}),enrichProfiles:false,acquirePreviewOperation:acquireOnce(),completePreviewOperation:noOp,loadAnalysisData:async()=>emptyData});const response=await handler(request());const payload=await response.json();assert.equal(response.status,200);assert.equal(payload.success,true);assert.equal(payload.preview.editions.length,23);assert.equal(payload.analysis.summary.catalogStatus,"NEW");assert.equal("html" in payload,false);});
test("preview moves a newly created session into extraction before it becomes ready",async()=>{resetIranKetabPreviewLimiterForTests();const html=await readFile("packages/iranketab-extractor/fixtures/white-nights/raw-page.html","utf8");const stages:string[]=[];const handler=createIranKetabPreviewPost({authorize:async()=>({user:{id:"admin-1"}}) as never,secureFetch:async canonicalUrl=>({canonicalUrl,html}),enrichProfiles:false,acquirePreviewOperation:acquireOnce(),completePreviewOperation:noOp,loadAnalysisData:async()=>emptyData,startSession:async()=>{stages.push("CREATED");return "session-1";},sessionStarted:async()=>{stages.push("EXTRACTING");},previewReady:async()=>{stages.push("PREVIEW_READY");}});const response=await handler(request());assert.equal(response.status,200);assert.deepEqual(stages,["CREATED","EXTRACTING","PREVIEW_READY"]);});
test("preview rejects a redirect that changes the IranKetab book identity",async()=>{resetIranKetabPreviewLimiterForTests();const handler=createIranKetabPreviewPost({authorize:async()=>({user:{id:"admin-1"}}) as never,secureFetch:async()=>({canonicalUrl:"https://www.iranketab.ir/book/2-other",html:"<html/>"}),acquirePreviewOperation:acquireOnce(),completePreviewOperation:noOp,failPreviewOperation:noOp,loadAnalysisData:async()=>emptyData});const response=await handler(request());const payload=await response.json();assert.equal(response.status,400);assert.deepEqual(payload.error,{code:"REDIRECT_REJECTED",message:"تغییر مسیر به صفحه کتاب دیگری رد شد.",retryable:false});});
test("concurrent equivalent URLs acquire one preview pipeline and followers receive its operation",async()=>{resetIranKetabPreviewLimiterForTests();const html=await readFile("packages/iranketab-extractor/fixtures/white-nights/raw-page.html","utf8");let acquired=false,fetches=0,analyses=0;const acquire=async()=>{if(!acquired){acquired=true;return {kind:"ACQUIRED" as const,operation:operation()};}return {kind:"PROCESSING" as const,operation:operation(),retryAfterSeconds:30};};const makeHandler=()=>createIranKetabPreviewPost({authorize:async()=>({user:{id:`admin-${Math.random()}`}}) as never,enrichProfiles:false,acquirePreviewOperation:acquire,completePreviewOperation:noOp,secureFetch:async canonicalUrl=>{fetches+=1;await new Promise(resolve=>setTimeout(resolve,30));return {canonicalUrl,html};},loadAnalysisData:async()=>{analyses+=1;return emptyData;}});const responses=await Promise.all([request(),request("https://www.iranketab.ir/book/1045-white-nights?utm_source=test"),request("https://www.iranketab.ir/book/1045-white-nights#pts=2405")].map((input,index)=>makeHandler()(input).then(async response=>({status:response.status,payload:await response.json(),index}))));assert.equal(fetches,1);assert.equal(analyses,1);assert.equal(responses.filter(item=>item.status===200).length,1);assert.equal(responses.filter(item=>item.status===202).length,2);assert.ok(responses.filter(item=>item.status===202).every(item=>item.payload.operationId==="operation-1"));});
